### ISSUE TITLE
请问可以提供一个简单跑起来的例子吗?包含redis,数据库的

### ISSUE THREAD

**Issue by wadjsnkk** [jwpttcg66/NettyGameServer#1]
请问可以提供一个跑起来的例子吗?包含redis,数据库的,最近在了解这方面的知识,谢谢.

**Comment by jwpttcg66** [comment]
启动gameserver类，启动服务器
test下game包，rpc包 启动对应客户端   

数据库方面正在开发，暂时还没有上传 https://github.com/jwpttcg66/spring-sharding-mybaits.git 基本原型是这个

**Comment by jwpttcg66** [comment]
db部分地址为GameShardingDb https://github.com/jwpttcg66/GameShardingDb.git可以提供数据存储服务了

**Comment by jwpttcg66** [comment]
工程已经集成db了，可参考test下jdbc,sql也已经放入了
