### ISSUE TITLE
是否有必要独立出 Loggers && ServiceName

### ISSUE THREAD

**Issue by xm-tech** [jwpttcg66/NettyGameServer#12]
@jwpttcg66
目前  [Loggers](https://github.com/jwpttcg66/NettyGameServer/blob/master/game-common/src/main/java/com/snowcattle/game/common/constant/Loggers.java) 以静态工厂的形式提供 Logger 的访问，我想本意应是好管理日志, 对整个系统有哪些日志掌控性更好。
但从 OCP 的角度出发，代码应对扩展开放，而对增删类型的修改关闭。
同时现在 的 成员属性中，存在具体业务逻辑的日志定义，也就是说之后有新的日志需求还是要修改 Loggers . 
基于以上分析，是不是 Logger 的定义还是内聚到对应的具体调用类里面会更好点呢？
同理 [ServiceName](https://github.com/jwpttcg66/NettyGameServer/blob/master/game-common/src/main/java/com/snowcattle/game/common/constant/ServiceName.java)

**Comment by xm-tech** [comment]
@jwpttcg66
目前  [Loggers](https://github.com/jwpttcg66/NettyGameServer/blob/master/game-common/src/main/java/com/snowcattle/game/common/constant/Loggers.java) 以静态工厂的形式提供 Logger 的访问，我想你本意应是好管理日志, 对整个系统有哪些日志掌控性更好。
但从 OCP 的角度出发，代码应对扩展开放，而对增删类型的修改关闭。
同时现在 的 成员属性中，存在具体业务逻辑的日志定义，也就是说之后有新的日志需求还是要修改 Loggers . 
基于以上分析，建议将 Logger 的定义还是内聚到对应的具体调用类里面

**Comment by jwpttcg66** [comment]
放入内部的话，找日志不方便。修改日志级别也麻烦。
