### ISSUE TITLE
There is a Runtime Exception

### ISSUE THREAD

**Issue by Liloveyang** [jwpttcg66/NettyGameServer#27]
Hello,

First of all i want to thank you for sharing your code.
But when I was operating some of my files, there was a NumberFormatException.
I found that it was thrown by the Integer.parseInt  method in 
game-common/src/main/java/com/snowcattle/game/common/util/ArrayUtils.java
 
```java
public static Set<Integer> getIntegerSet(List<String> ids) {
		Set<Integer> list = new HashSet<Integer>();
		for(String key: ids){
			list.add(Integer.parseInt(key));
		}
		return list;
	}
```

There is also a potential null pointer exception in method 
game-common/src/main/java/com/snowcattle/game/common/util/FileUtil.getConfigPath(String fileName), such as when the getResource(fileName) method return null
```java
public static String getConfigPath(String fileName)
{
	ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
	return classLoader.getResource(fileName).getPath();
}
```

However, I didn't know that this exception would happen before, resulting in a sudden interruption of my operation,

so I suggest you add catch or throw to the source code An exception goes out, which is convenient for the caller to develop.

Thank you!

**Comment by Liloveyang** [comment]
I also found that some methods have potential exceptions in the other two files
1. game-common/src/main/java/com/snowcattle/game/common/util/JsonUtils.java
```java
@SuppressWarnings("unchecked")
    public static Map<String,String> getMapFromJson(String json){
        return JSON.parseObject(json, Map.class);
    }
```
If the parameter JSON does not meet the map requirements, jsonexception will be thrown！
2. game-common/src/main/java/com/snowcattle/game/common/util/RandomUtil.java
```java
public static int getRadomIndex(List<Integer> listRate,int rateMaxNum) {
		int left = 0;
		int right;
		int index = -1;
		int random = nextInt(0, rateMaxNum);
		for(int i=0; i < listRate.size(); i++){
			right = left + listRate.get(i);
			if(random >= left && random < right){
				index = i;
				break;
			}
			left = right;
		}
		return index;
	}

public static int nextInt(int randomMin, int randomMax) {
		int randomBase = randomMax - randomMin;
		if (randomBase < 0) {
			throw new IllegalArgumentException(
					"randomMax must be bigger than randomMin");
		} else if (randomBase == 0) {
			return randomMin;
		} else {
			return (random.nextInt(randomBase) + randomMin);
		}
	}
```
getradomindex method calls nextint method, but there is illegalargumentexception thrown in nextint method, so getradomindex should throw or try catch module.

Thank you!

**Comment by jwpttcg66** [comment]
thanks for your help
