### ISSUE TITLE
Found potential runtime exception

### ISSUE THREAD

**Issue by Wushuyi123** [jwpttcg66/NettyGameServer#29]
Hello,
First of all i want to thank you for sharing your code.
But when I was operating some of my files, there were runtime exception of the type 'java.lang.RuntimeException' and 'java.lang.IlegalArgumentException'. The runtime exceptions were from methods:

1. com.snowcattle.game.common.util.getIntArrayAttriValue()
```
	public static int[] getIntArrayAttriValue(Element e, String attrName) {
		String[] temp = e.getAttributeValue(attrName).split(ARRAY_SEPARATOR);
		int[] result = new int[temp.length];
		for (int i = 0; i < temp.length; i++) {
			result[i] = Integer.valueOf(temp[i]);
		}
		return result;
	}
```

2. com.snowcattle.game.common.util.PropertyRawSet.getInt(java.lang.K,java.lang.int)
```
	public int getInt(K key, int defVal) {
		Number val = (Number) p.get(key);
		if (val == null) {
			return defVal;
		}
		return val.intValue();
	}

```
it might cause the program to crash. But the caller may not know these problems and may cause the program to crash suddenly.
so I suggest you add catch or throw to the source code An exception goes out, which is convenient for the caller to develop. Thank you!
The issue can be reproduced by 1. passing a non-number string 2. passing a value that can't be parsed to a Number class.

**Comment by jwpttcg66** [comment]
thanks for your help
