### ISSUE TITLE
包没有做粘包处理

### ISSUE THREAD

**Issue by haoshijing** [jwpttcg66/NettyGameServer#4]
在解析数据包的时候都没有做粘包处理

**Comment by jwpttcg66** [comment]
netty底层已经自带处理了

**Comment by haoshijing** [comment]
在你的包解析是直接继承的 MessageToMessageDecoder , netty黏包处理应该是继承 LengthFieldBasedFrameDecoder 这个吗

**Comment by jwpttcg66** [comment]
嗯，是的
